name: ChatFarsi
main: GameParrot\PingView\Main
src-namespace-prefix: GameParrot\PingView
version: 1.0.0
api: [4.0.0, 5.21.1]
load: POSTWORLD
author: ShahabManoochehri
description:
website: https://null.com
